name: Build and Publish Web

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and deploy @aladdin/web
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.21

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build web app
        working-directory: apps/web
        run: bun run build

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist

      - name: Publish dist to web branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin web || true

          DEPLOY_DIR=$(mktemp -d)

          if git rev-parse --verify origin/web >/dev/null 2>&1; then
            git worktree add "$DEPLOY_DIR" origin/web
          else
            git worktree add -b web "$DEPLOY_DIR"
          fi

          rsync -av --delete --exclude '.git' apps/web/dist/ "$DEPLOY_DIR"/

          cd "$DEPLOY_DIR"
          git add --all

          if git diff --quiet --cached; then
            echo "No changes to publish"
            exit 0
          fi

          COMMIT_MESSAGE="Deploy web $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git commit -m "$COMMIT_MESSAGE"
          git push origin HEAD:web
