[phases.setup]
nixpkgs = ["bun"]

[phases.install]
cmds = [
  "bun install --cwd ../.."
]

[phases.build]
cmds = [
  "bun run build"
]

[start]
cmd = "bun run serve -- --host 0.0.0.0 --port ${PORT:-4173}"

[environment]
NODE_ENV = "production"
